---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Include version-specific variables for Alpine
  include_vars: "Alpine.yml"
  when: ansible_os_family == "Alpine"

# FIXME! as redhat epel has still ansible 1.9. need to disable those 2 lines when testing this platform
- include: loki-windows.yml
  when: ansible_os_family == 'Windows'

- include: loki.yml
  when: ansible_os_family != 'Windows'

- name: Recover files on orchestrator
  fetch: "src={{ loki_output }} dest=tmp/"
  when: do_fetch is defined and do_fetch

